terraform import azurerm_private_dns_zone_virtual_network_link.vnet1 /subscriptions/dba4487b-db2f-4d73-89bd-699efaef771c/resourceGroups/mohdg-gulmaan-banking-rg-region1-dev/providers/Microsoft.Network/privateDnsZones/internal.banking.com/virtualNetworkLinks/link-vnet1
terraform import azurerm_private_dns_zone_virtual_network_link.vnet2 /subscriptions/dba4487b-db2f-4d73-89bd-699efaef771c/resourceGroups/mohdg-gulmaan-banking-rg-region1-dev/providers/Microsoft.Network/privateDnsZones/internal.banking.com/virtualNetworkLinks/link-vnet2
terraform import azuread_user.admin_walter walter@mohdgulman87outlook.onmicrosoft.com
terraform import azuread_user.auditor_skyler skyler@mohdgulman87outlook.onmicrosoft.com
terraform import azuread_user.dev_jesse jesse@mohdgulman87outlook.onmicrosoft.com
terraform import azuread_user.dev_hank hank@mohdgulman87outlook.onmicrosoft.com
terraform import azuread_user.data_mike mike@mohdgulman87outlook.onmicrosoft.com
terraform import azuread_user.regional_tuco tuco@mohdgulman87outlook.onmicrosoft.com
terraform import azuread_user.soc_huell huell@mohdgulman87outlook.onmicrosoft.com
terraform import azuread_user.devops_gomez gomez@mohdgulman87outlook.onmicrosoft.com
terraform import 'module.subnets_extended_1.azurerm_subnet.this["management"]' /subscriptions/dba4487b-db2f-4d73-89bd-699efaef771c/resourceGroups/mohdg-gulmaan-banking-rg-region1-dev/providers/Microsoft.Network/virtualNetworks/mohdg-gulmaan-banking-vnet-region1-dev/subnets/mohdg-gulmaan-banking-ext-r1-subnet-management-dev
