terraform import azuread_user.admin_walter walter@mohdgulman87outlook.onmicrosoft.com
terraform import azuread_user.auditor_skyler skyler@mohdgulman87outlook.onmicrosoft.com
terraform import azuread_user.dev_jesse jesse@mohdgulman87outlook.onmicrosoft.com
terraform import azuread_user.dev_hank hank@mohdgulman87outlook.onmicrosoft.com
terraform import azuread_user.data_mike mike@mohdgulman87outlook.onmicrosoft.com
terraform import azuread_user.regional_tuco tuco@mohdgulman87outlook.onmicrosoft.com
terraform import azuread_user.soc_huell huell@mohdgulman87outlook.onmicrosoft.com
terraform import azuread_user.devops_gomez gomez@mohdgulman87outlook.onmicrosoft.com
